### ISSUE TITLE
error while loading shared libraries: libboost_filesystem.so.1.58.0

### ISSUE THREAD

**Issue by SamaelDNM** [allforonebusiness/binaries-linux-18.04#1]
Hi Dev, I have the following error if you can help me solve it

_error while loading shared libraries: libboost_filesystem.so.1.58.0: cannot open shared object file: No such file or directory_

![IMG_20191207_162609_031](https://user-images.githubusercontent.com/36386371/70380262-8d5adc00-190e-11ea-8418-bd73b127a052.jpg)

**Comment by kgcdream2019** [comment]
Hello, What version of ubuntu OS did you use to run it? 16.04 or 18.04?

**Comment by kgcdream2019** [comment]
It seems you didn't install any libraries for allforonebusinessd.
please try such that:

sudo apt-get install build-essential libtool bsdmainutils autotools-dev autoconf pkg-config automake python3 libssl1.0-dev libgmp-dev libevent-dev libboost-all-dev software-properties-common
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev libminiupnpc-dev libzmq3-dev
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 libqt5svg5-dev libqt5charts5-dev qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev

And then run allforonebusinessd again.

**Comment by SamaelDNM** [comment]
I already have that dependency installed, I am using Ubuntu 18.04, in the previous version I did not have this problem

**Comment by SamaelDNM** [comment]
with the previous version I didn't get this problem

**Comment by SamaelDNM** [comment]
I see that you updated the name, I have downloaded it again and now it works again, I am in the latest version, right?


![Screenshot_2019-12-09-16-37-31-216_com sonelli juicessh](https://user-images.githubusercontent.com/36386371/70470825-4aca0880-1aa2-11ea-82d7-4fbfffbffc7f.jpg)
